wandb_version: 1

number_chargelevels:
  desc: null
  value: 19
number_spatial_nodes:
  desc: null
  value: 5
dataset:
  desc: null
  value: data/SF/5/SF_5.json
episodes:
  desc: null
  value: 9000
number_vehicles_per_node_init:
  desc: null
  value: 23
charging_stations:
  desc: null
  value:
  - true
  - true
  - true
  - true
  - true
charging_station_capacities:
  desc: null
  value:
  - 257.0
  - 257.0
  - 257.0
  - 257.0
  - 257.0
learning_rate_actor:
  desc: null
  value: 0.001
learning_rate_critic:
  desc: null
  value: 0.001
gradient_norm_clip_actor:
  desc: null
  value: 0.5
gradient_norm_clip_critic:
  desc: null
  value: 0.5
scale_factor:
  desc: null
  value: 1.0e-05
scale_price:
  desc: null
  value: 0.1
time_horizon:
  desc: null
  value: 48
episode_length:
  desc: null
  value: 48
seed:
  desc: null
  value: 10
charge_levels_per_timestep:
  desc: null
  value: 6
licence:
  desc: null
  value: Aaryan
_wandb:
  desc: null
  value:
    python_version: 3.9.2
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695879422.54247
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 13
      - 16
      - 23
      4: 3.9.2
      5: 0.15.10
      8:
      - 5
